ALTER TABLE EMPLOYEE  ADD constraint companyFK1 FOREIGN KEY(Super_ssn)
REFERENCES EMPLOYEE (Ssn);

ALTER TABLE EMPLOYEE  ADD constraint companyFK2 FOREIGN KEY(Dno)
REFERENCES DEPARTMENT (Dnumber);

ALTER TABLE WORKS_ON ADD constraint companyFK3 FOREIGN KEY(Essn)
REFERENCES EMPLOYEE (Ssn);

ALTER TABLE WORKS_ON  ADD constraint companyFK4 FOREIGN KEY(Pno)
REFERENCES PROJECT (Pnumber);

ALTER TABLE DEPT_LOCATIONS  ADD constraint companyFK5 FOREIGN KEY(Dnumber)
REFERENCES DEPARTMENT (Dnumber);

ALTER TABLE DEPENDENT  ADD constraint companyFK6 FOREIGN KEY(Essn)
REFERENCES EMPLOYEE (Ssn);

ALTER TABLE DEPARTMENT  ADD constraint companyFK7 FOREIGN KEY(Mgr_ssn)
REFERENCES EMPLOYEE (Ssn);

ALTER TABLE PROJECT  ADD constraint companyFK8 FOREIGN KEY (Dnum)
REFERENCES DEPARTMENT (Dnumber);