
DROP TABLE IF EXISTS EMPLOYEE CASCADE;
DROP TABLE IF EXISTS DEPARTMENT CASCADE;
DROP TABLE IF EXISTS DEPT_LOCATIONS CASCADE;
DROP TABLE IF EXISTS PROJECT CASCADE;
DROP TABLE IF EXISTS WORKS_ON CASCADE;
DROP TABLE IF EXISTS DEPENDENT CASCADE;

